/* automatically generated by rust-bindgen 0.72.1 */

pub type ipnumber = f64;
pub type ipindex = ::std::os::raw::c_int;
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ApplicationReturnStatus {
    Solve_Succeeded = 0,
    Solved_To_Acceptable_Level = 1,
    Infeasible_Problem_Detected = 2,
    Search_Direction_Becomes_Too_Small = 3,
    Diverging_Iterates = 4,
    User_Requested_Stop = 5,
    Feasible_Point_Found = 6,
    Maximum_Iterations_Exceeded = -1,
    Restoration_Failed = -2,
    Error_In_Step_Computation = -3,
    Maximum_CpuTime_Exceeded = -4,
    Maximum_WallTime_Exceeded = -5,
    Not_Enough_Degrees_Of_Freedom = -10,
    Invalid_Problem_Definition = -11,
    Invalid_Option = -12,
    Invalid_Number_Detected = -13,
    Unrecoverable_Exception = -100,
    NonIpopt_Exception_Thrown = -101,
    Insufficient_Memory = -102,
    Internal_Error = -199,
}
pub const AlgorithmMode_RegularMode: AlgorithmMode = 0;
pub const AlgorithmMode_RestorationPhaseMode: AlgorithmMode = 1;
pub type AlgorithmMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IpoptProblemInfo {
    _unused: [u8; 0],
}
pub type IpoptProblem = *mut IpoptProblemInfo;
pub type UserDataPtr = *mut ::std::os::raw::c_void;
pub type Eval_F_CB = ::std::option::Option<
    unsafe extern "C" fn(
        n: ipindex,
        x: *mut ipnumber,
        new_x: bool,
        obj_value: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> bool,
>;
pub type Eval_Grad_F_CB = ::std::option::Option<
    unsafe extern "C" fn(
        n: ipindex,
        x: *mut ipnumber,
        new_x: bool,
        grad_f: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> bool,
>;
pub type Eval_G_CB = ::std::option::Option<
    unsafe extern "C" fn(
        n: ipindex,
        x: *mut ipnumber,
        new_x: bool,
        m: ipindex,
        g: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> bool,
>;
pub type Eval_Jac_G_CB = ::std::option::Option<
    unsafe extern "C" fn(
        n: ipindex,
        x: *mut ipnumber,
        new_x: bool,
        m: ipindex,
        nele_jac: ipindex,
        iRow: *mut ipindex,
        jCol: *mut ipindex,
        values: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> bool,
>;
pub type Eval_H_CB = ::std::option::Option<
    unsafe extern "C" fn(
        n: ipindex,
        x: *mut ipnumber,
        new_x: bool,
        obj_factor: ipnumber,
        m: ipindex,
        lambda: *mut ipnumber,
        new_lambda: bool,
        nele_hess: ipindex,
        iRow: *mut ipindex,
        jCol: *mut ipindex,
        values: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> bool,
>;
pub type Intermediate_CB = ::std::option::Option<
    unsafe extern "C" fn(
        alg_mod: ipindex,
        iter_count: ipindex,
        obj_value: ipnumber,
        inf_pr: ipnumber,
        inf_du: ipnumber,
        mu: ipnumber,
        d_norm: ipnumber,
        regularization_size: ipnumber,
        alpha_du: ipnumber,
        alpha_pr: ipnumber,
        ls_trials: ipindex,
        user_data: UserDataPtr,
    ) -> bool,
>;
unsafe extern "C" {
    pub fn CreateIpoptProblem(
        n: ipindex,
        x_L: *mut ipnumber,
        x_U: *mut ipnumber,
        m: ipindex,
        g_L: *mut ipnumber,
        g_U: *mut ipnumber,
        nele_jac: ipindex,
        nele_hess: ipindex,
        index_style: ipindex,
        eval_f: Eval_F_CB,
        eval_g: Eval_G_CB,
        eval_grad_f: Eval_Grad_F_CB,
        eval_jac_g: Eval_Jac_G_CB,
        eval_h: Eval_H_CB,
    ) -> IpoptProblem;
}
unsafe extern "C" {
    pub fn FreeIpoptProblem(ipopt_problem: IpoptProblem);
}
unsafe extern "C" {
    pub fn AddIpoptStrOption(
        ipopt_problem: IpoptProblem,
        keyword: *mut ::std::os::raw::c_char,
        val: *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn AddIpoptNumOption(
        ipopt_problem: IpoptProblem,
        keyword: *mut ::std::os::raw::c_char,
        val: ipnumber,
    ) -> bool;
}
unsafe extern "C" {
    pub fn AddIpoptIntOption(
        ipopt_problem: IpoptProblem,
        keyword: *mut ::std::os::raw::c_char,
        val: ipindex,
    ) -> bool;
}
unsafe extern "C" {
    pub fn OpenIpoptOutputFile(
        ipopt_problem: IpoptProblem,
        file_name: *mut ::std::os::raw::c_char,
        print_level: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn SetIpoptProblemScaling(
        ipopt_problem: IpoptProblem,
        obj_scaling: ipnumber,
        x_scaling: *mut ipnumber,
        g_scaling: *mut ipnumber,
    ) -> bool;
}
unsafe extern "C" {
    pub fn SetIntermediateCallback(
        ipopt_problem: IpoptProblem,
        intermediate_cb: Intermediate_CB,
    ) -> bool;
}
unsafe extern "C" {
    pub fn IpoptSolve(
        ipopt_problem: IpoptProblem,
        x: *mut ipnumber,
        g: *mut ipnumber,
        obj_val: *mut ipnumber,
        mult_g: *mut ipnumber,
        mult_x_L: *mut ipnumber,
        mult_x_U: *mut ipnumber,
        user_data: UserDataPtr,
    ) -> ApplicationReturnStatus;
}
